### ISSUE TITLE
Representations that can be computed ultra quickly by leveraging the knowledge of the ancients

### ISSUE THREAD

**Issue by dmarx** [jdagdelen/hyperDB#10]
I've heard rumors of traditional nlp techniques used by tribal elders that are able to achieve knowledge representations *without even using deep learning*. The techniques even sound magical, with names like *"bag of words"* and *"intersection over union"*. You might be able to find some useful references in the archaeology literature.

**Comment by jdagdelen** [comment]
Some cuneiform tablets have recently been found with a strange rune on them: ɟpıɟʇ

I wonder what it could mean?
