### ISSUE TITLE
Term sheet

### ISSUE THREAD

**Issue by tdb-alcorn** [jdagdelen/hyperDB#18]
Dear HyperDB gmbh,

We at Trendly VC are excited to offer you a seed investment of $5 million for your cutting-edge, buzzworthy, and undeniably innovative vector database technology. We are confident that this investment will take your company to the moon and beyond!

Below are the terms of our investment:

**Valuation:** $100 million pre-money valuation, $105 million post-money valuation.

**Convertible note:** This investment will be made in the form of a convertible note, which will convert into equity upon the company's next funding round or liquidity event, whichever occurs first.

**Liquidation preference:** Trendly VC will have a 2x liquidation preference over common stockholders in the event of a liquidation or sale of the company.

**Board seat:** Trendly VC will have the right to appoint one board member to hypoDB's board of directors.

**Trendly VC hype package:** As part of this investment, Trendly VC will provide hypeDB with a customized package of trendy buzzwords, including "synergy," "disruptive," "game-changing," and "unicorn potential." We believe these buzzwords will help hypedB attract additional investment and media attention.

We look forward to working with you and helping you ride the hype train to success!

Best regards,
Trendly VC

**Comment by jdagdelen** [comment]
Make it $10M and you have a deal. 

You also have to attend my annual Holiday Party (homemade eggnog!)

**Comment by jdagdelen** [comment]
You also have to attend my annual Christmas Party (homemade eggnog!)

**Comment by tdb-alcorn** [comment]
You're a tough negotiator - I like that. $15M, final offer.

And hold the eggnog, I'm on the Longo diet and aiming to be the first human to break the 200yo barrier. Your vector database technology is a big part of my plan.

**Comment by jdagdelen** [comment]
Ok, deal!
