### ISSUE TITLE
Query to understand performance of hyperDB

### ISSUE THREAD

**Issue by codeastra2** [jdagdelen/hyperDB#19]
Hi, firstly thanks a lot for this! 

I was looking at the implementation of the files and tried to figure out what makes the performance better than other dbs? 
1. I could not find any direct usage of MKL BLAS library , is it somehow internally implemented ? 
2. Is the search proving to be the speed up , with the OpenAI embeddings the metric(cosine similarity) seems to be helping in retrieving the queries faster... 
It would be great if you could help with my queries thanks!

**Comment by jdagdelen** [comment]
The numpy backend is hardware accelerated with MKRL and BLAS.
