### ISSUE TITLE
pypi version out of date

### ISSUE THREAD

**Issue by rysuds** [jdagdelen/hyperDB#21]
Love the project! Just wanted to point out that the `pip` version of the library does not have `return_similarities` as a parameter on `HyperDB.query`

**Comment by jdagdelen** [comment]
Fixed. See v0.1.3

**Comment by rysuds** [comment]
Looks like pypi is still at `0.1.1` https://pypi.org/project/hyperdb/

**Comment by rysuds** [comment]
Oh nvm im very dumb, wrong page
